---
version: '3'
services:
  json-rpc-server:
    image: shardus/json-rpc-server:dev
    build:
      context: .
    restart: unless-stopped
    network_mode: host
    configs:
      - source: archiverconfig
        uid: node
        gid: node
        target: /home/node/app/archiverConfig.json

configs:
  archiverconfig:
    file: ./archiverConfig.json
